---
title: "EUROMOD scenarios"
# format: docx
format: html
execute:
  echo: false
---

```{r}
#| include: false

library(data.table, quietly = TRUE)
library(foreach)
library(ggpubr, quietly = TRUE)

columns <- c("idhh", "dag", "ils_dispy", "ils_ben", "bsauc_s")
scenarios <- c("baseline", "mis", "flat", "dk")
years <- 2023:2029

data <- foreach(year = years, .combine = rbind) %:%
  foreach(scenario = scenarios, .combine = rbind) %do% {
    cat(".")
    data <- fread(
      here::here("data", "euromod_output", scenario, paste0("uk_", year,  "_std.txt")),
      select = columns
    )
    data$year <- year
    data$scenario <- scenario
    data
  }

by_hh <- data[, .(
  eq = 1 + 0.5 * (sum(dag >= 14) - 1) + 0.3 * (sum(dag <= 13)),
  ils_dispy = sum(ils_dispy),
  ils_ben = sum(ils_ben),
  any_uc = sum(bsauc_s) > 0
), by = c("scenario", "year", "idhh")]

by_hh[, ils_dispy_eq := ils_dispy / eq]
by_hh[, ils_ben_eq := ils_ben / eq]
by_hh[, scenario := factor(
  scenario,
  levels = c("baseline", "mis", "flat", "dk"),
  labels = c("Baseline", "Progressive tax", "Flat tax", "Increased benefits")
)]
by_hh[, inc_decile := dplyr::ntile(ils_dispy_eq, 10), by = c("scenario", "year")]

baseline_deciles <- by_hh[scenario == "Baseline", .(year, idhh, inc_decile_baseline = inc_decile)]

common_layers <- list(
  geom_line(aes(color = scenario, linetype = scenario)),
  geom_point(aes(color = scenario, shape = scenario)),
  scale_color_brewer(palette = "Set1"),
  theme_pubr()
)
```

```{r}
#| fig-width: 10
#| fig-height: 5
by_hh |>
  merge(baseline_deciles, by = c("idhh", "year")) |>
  _[, .(ils_dispy_eq = mean(ils_dispy_eq)), by = c("scenario", "year", "inc_decile_baseline")] |>
  ggplot() +
  aes(x = year, y = ils_dispy_eq) +
  labs(title = "Equivalised household disposable income by baseline income decile", x = "Year", y = "GBP per year") +
  facet_wrap("inc_decile_baseline", scales = "free", ncol = 5) +
  scale_x_continuous(breaks = c(2023, 2026, 2029)) +
  common_layers
```

```{r}
#| fig-width: 10
#| fig-height: 5
by_hh |>
  merge(baseline_deciles, by = c("idhh", "year")) |>
  _[, .(ils_ben_eq = mean(ils_ben_eq)), by = c("scenario", "year", "inc_decile_baseline")] |>
  ggplot() +
  aes(x = year, y = ils_ben_eq) +
  labs(title = "Equivalised benefit income by baseline income decile", x = "Year", y = "GBP per year") +
  facet_wrap("inc_decile_baseline", scales = "free", ncol = 5) +
  scale_x_continuous(breaks = c(2023, 2026, 2029)) +
  common_layers
```

```{r}
#| fig-width: 10
#| fig-height: 5
by_hh |>
  merge(baseline_deciles, by = c("idhh", "year")) |>
  _[, .(any_uc = mean(any_uc)), by = c("scenario", "year", "inc_decile_baseline")] |>
  ggplot() +
  aes(x = year, y = any_uc) +
  labs(title = "Prevalence of receiving Universal Credit by baseline income decile", x = "Year", y = "Proportion") +
  facet_wrap("inc_decile_baseline", scales = "free", ncol = 5) +
  scale_x_continuous(breaks = c(2023, 2026, 2029)) +
  common_layers
```
