---
title: "SimPaths results"
# format: docx
format: html
execute:
  echo: false
---

```{r}
#| include: false

library(data.table, quietly = TRUE)
library(ggpubr, quietly = TRUE)

raw_data <- rbindlist(list(
  baseline  = fread(here::here("data", "simpaths_output", "baseline", "summarised_output.csv")),
  dk        = fread(here::here("data", "simpaths_output", "dk", "summarised_output.csv")),
  flat      = fread(here::here("data", "simpaths_output", "flat", "summarised_output.csv")),
  mis       = fread(here::here("data", "simpaths_output", "mis", "summarised_output.csv"))
))

subgroups <- c("inc_decile", "inc_quintile", "demMaleFlag", "eduHighestC4", "age_cat")

summary_vars <- c(
  "mean_mcscase45",
  "emp_rate",
  "mean_inc",
  "gini",
  "median_share",
  "s80s20",
  "rii",
  "sii"
)

data <- raw_data[, c(
    list(runs = .N),
    lapply(.SD, median, na.rm = TRUE) |> setNames(summary_vars),
    lapply(.SD, quantile, probs = 0.025, na.rm = TRUE) |> setNames(paste0(summary_vars, "_l")),
    lapply(.SD, quantile, probs = 0.975, na.rm = TRUE) |> setNames(paste0(summary_vars, "_u"))
  ),
  by = c("strata", subgroups, "scenario", "time"),
  .SDcols = summary_vars
]
data[, scenario := factor(
  scenario,
  levels = c("baseline", "mis", "flat", "dk"),
  labels = c("Baseline", "Progressive tax", "Flat tax", "Increased benefits")
)]

comparison <- merge(
  raw_data[scenario != "baseline"],
  raw_data[scenario == "baseline"],
  by = c("seed", "time", "strata", subgroups),
  suffixes = c(".int", ".bln")
)
for (varname in summary_vars) {
  set(
    comparison,
    j = paste0(varname, ".diff"),
    value = comparison[[paste0(varname, ".int")]] - comparison[[paste0(varname, ".bln")]]
  )
}
effects <- comparison[, c(
    list(runs = .N),
    lapply(.SD, median, na.rm = TRUE) |> setNames(summary_vars),
    lapply(.SD, quantile, probs = 0.025, na.rm = TRUE) |> setNames(paste0(summary_vars, "_l")),
    lapply(.SD, quantile, probs = 0.975, na.rm = TRUE) |> setNames(paste0(summary_vars, "_u"))
  ),
  by = c("strata", subgroups, "scenario.int", "time"),
  .SDcols = paste0(summary_vars, ".diff")
]
```

## MCS caseness

```{r}
#| width: 5
#| height: 3
common_layers <- list(
  geom_line(aes(color = scenario)),
  geom_point(aes(color = scenario, shape = scenario, fill = scenario)),
  geom_ribbon(aes(fill = scenario), alpha = 0.05),
  scale_shape_manual(values = c(20, 21, 22, 24)),
  scale_color_manual(values = c("black", "red3", "slateblue3", "springgreen4")),
  scale_fill_manual(values = c("black", "red3", "slateblue3", "springgreen4")),
  theme_pubr()
)

data[strata == "population"] |>
  _[time >= 2026] |>
  ggplot() +
  aes(x = time, y = mean_mcscase45, ymin = mean_mcscase45_l, ymax = mean_mcscase45_u) +
  labs(title = "Prevalence of MCS caseness in the population", x = "Year", y = "Prevalence") +
  scale_y_continuous(labels = scales::percent) +
  common_layers
```

```{r}
data[inc_decile == 1] |>
  _[time >= 2026] |>
  ggplot() +
  aes(x = time, y = mean_mcscase45, ymin = mean_mcscase45_l, ymax = mean_mcscase45_u) +
  labs(title = "Prevalence of MCS caseness in the bottom income decile", x = "Year", y = "Prevalence") +
  scale_x_continuous(breaks = scales::breaks_pretty()) +
  common_layers
```

## Employment rate

```{r}
data[strata == "population"] |>
  _[time >= 2026] |>
  ggplot() +
  aes(x = time, y = emp_rate, ymin = emp_rate_l, ymax = emp_rate_u) +
  labs(title = "Employment rate in the population", x = "Year", y = "Rate") +
  scale_x_continuous(breaks = scales::breaks_pretty()) +
  common_layers
```

```{r}
data[inc_decile == 1] |>
  _[time >= 2026] |>
  ggplot() +
  aes(x = time, y = emp_rate, ymin = emp_rate_l, ymax = emp_rate_u) +
  labs(title = "Employment rate in the bottom income decile", x = "Year", y = "Rate") +
  scale_x_continuous(breaks = scales::breaks_pretty()) +
  common_layers
```

## Inequality in MCS caseness

```{r}
data[strata == "population"] |>
  ggplot() +
  aes(x = time, y = sii, ymin = sii_l, ymax = sii_u) +
  labs(title = "Slope index of inequality", x = "Year", y = "Risk of MCS caseness") +
  scale_x_continuous(breaks = scales::breaks_pretty()) +
  common_layers
```

```{r}
data[strata == "population"] |>
  ggplot() +
  aes(x = time, y = rii, ymin = rii_l, ymax = rii_u) +
  labs(title = "Relative index of inequality", x = "Year", y = "RII") +
  scale_x_continuous(breaks = scales::breaks_pretty()) +
  common_layers
```

## Mean income

```{r}
data[inc_decile == 1] |>
  _[time >= 2026] |>
  ggplot() +
  aes(x = time, y = mean_inc, ymin = mean_inc_l, ymax = mean_inc_u) +
  labs(title = "Mean equivalised disposable household income (bottom decile)", x = "Year", y = "GBP per year") +
  scale_x_continuous(breaks = scales::breaks_pretty()) +
  common_layers
```

```{r}
data[inc_decile == 10] |>
  _[time >= 2026] |>
  ggplot() +
  aes(x = time, y = mean_inc, ymin = mean_inc_l, ymax = mean_inc_u) +
  labs(title = "Mean equivalised disposable household income (top decile)", x = "Year", y = "GBP per year") +
  scale_x_continuous(breaks = scales::breaks_pretty()) +
  common_layers
```

---

## Income inequality

```{r}
data[strata == "population"] |>
  _[time >= 2026] |>
  ggplot() +
  aes(x = time, y = gini, ymin = gini_l, ymax = gini_u) +
  labs(title = "Gini coefficient", x = "Year", y = "Gini coefficient") +
  scale_x_continuous(breaks = scales::breaks_pretty()) +
  common_layers
```

```{r}
data[strata == "population"] |>
  _[time >= 2026] |>
  ggplot() +
  aes(x = time, y = median_share, ymin = median_share_l, ymax = median_share_u) +
  labs(title = "Median share of income", subtitle = "Proportion of income earned by the bottom 50%", x = "Year", y = "Median share of income") +
  scale_x_continuous(breaks = scales::breaks_pretty()) +
  common_layers
```

```{r}
data[strata == "population"] |>
  _[time >= 2026] |>
  ggplot() +
  aes(x = time, y = s80s20, ymin = s80s20_l, ymax = s80s20_u) +
  labs(title = "S80/S20", subtitle = "Ratio of income share in the top quintile over income share in the bottom quintile", x = "Year", y = "S80/S20") +
  scale_x_continuous(breaks = scales::breaks_pretty()) +
  common_layers
```

## Subgroups

```{r}
data[strata == "demMaleFlag"] |>
  _[time >= 2026] |>
  ggplot() +
  aes(x = time, y = mean_mcscase45, ymin = mean_mcscase45_l, ymax = mean_mcscase45_u) +
  labs(title = "Prevalence of MCS caseness stratified by gender", x = "Year", y = "Prevalence") +
  facet_wrap("demMaleFlag") +
  scale_x_continuous(breaks = scales::breaks_pretty()) +
  common_layers
```

```{r}
data[strata == "eduHighestC4"] |>
  _[time >= 2026] |>
  ggplot() +
  aes(x = time, y = mean_mcscase45, ymin = mean_mcscase45_l, ymax = mean_mcscase45_u) +
  labs(title = "Prevalence of MCS caseness stratified by education", x = "Year", y = "Prevalence") +
  facet_wrap("eduHighestC4") +
  scale_x_continuous(breaks = scales::breaks_pretty()) +
  common_layers
```

```{r}
data[strata == "age_cat"] |>
  _[time >= 2026] |>
  ggplot() +
  aes(x = time, y = mean_mcscase45, ymin = mean_mcscase45_l, ymax = mean_mcscase45_u) +
  labs(title = "Prevalence of MCS caseness stratified by age", x = "Year", y = "Prevalence") +
  facet_wrap("age_cat") +
  scale_x_continuous(breaks = scales::breaks_pretty()) +
  common_layers
```

```{r}
#| fig-width: 10
#| fig-height: 5
data[strata == "inc_decile"] |>
  _[time >= 2026] |>
  ggplot() +
  aes(x = time, y = mean_mcscase45, ymin = mean_mcscase45_l, ymax = mean_mcscase45_u) +
  labs(title = "Prevalence of MCS caseness stratified by income decile", x = "Year", y = "Prevalence") +
  facet_wrap("inc_decile", scales = "free", ncol = 5) +
  scale_x_continuous(breaks = c(2026, 2030, 2034)) +
  common_layers
```

```{r}
#| fig-width: 10
#| fig-height: 5
data[strata == "inc_decile"] |>
  _[time >= 2026] |>
  ggplot() +
  aes(x = time, y = emp_rate, ymin = emp_rate_l, ymax = emp_rate_u) +
  labs(title = "Employment rate stratified by income decile", x = "Year", y = "Employment rate") +
  facet_wrap("inc_decile", scales = "free", ncol = 5) +
  scale_x_continuous(breaks = c(2026, 2030, 2034)) +
  common_layers
```

```{r}
#| fig-width: 10
#| fig-height: 5
data[strata == "inc_decile"] |>
  _[time >= 2026] |>
  ggplot() +
  aes(x = time, y = mean_inc, ymin = mean_inc_l, ymax = mean_inc_u) +
  labs(title = "Mean equivalised disposable household income stratified by income decile", x = "Year", y = "GBP per year") +
  facet_wrap("inc_decile", scales = "free", ncol = 5) +
  scale_x_continuous(breaks = c(2026, 2030, 2034)) +
  common_layers
```

## Change relative to baseline in 2035 (population)

```{r}
effects |>
  _[strata == "population"] |>
  _[time == 2035] |>
  ggplot() +
  aes(x = mean_mcscase45, xmin = mean_mcscase45_l, xmax = mean_mcscase45_u, y = scenario.int) +
  geom_pointrange() +
  geom_vline(xintercept = 0, linetype = "dashed") +
  theme_pubr()
```

```{r}
effects |>
  _[strata == "population"] |>
  _[time == 2035] |>
  ggplot() +
  aes(x = emp_rate, xmin = emp_rate_l, xmax = emp_rate_u, y = scenario.int) +
  geom_pointrange() +
  geom_vline(xintercept = 0, linetype = "dashed") +
  theme_pubr()
```

## Change relative to baseline in 2035 (subgroups)

```{r}
effects |>
  _[strata == "demMaleFlag"] |>
  _[time == 2035] |>
  ggplot() +
  aes(x = mean_mcscase45, xmin = mean_mcscase45_l, xmax = mean_mcscase45_u, y = scenario.int) +
  geom_pointrange() +
  geom_vline(xintercept = 0, linetype = "dashed") +
  facet_wrap(~demMaleFlag) +
  theme_pubr()
```

```{r}
effects |>
  _[strata == "eduHighestC4"] |>
  _[time == 2035] |>
  ggplot() +
  aes(x = mean_mcscase45, xmin = mean_mcscase45_l, xmax = mean_mcscase45_u, y = scenario.int) +
  geom_pointrange() +
  geom_vline(xintercept = 0, linetype = "dashed") +
  facet_wrap(~eduHighestC4) +
  theme_pubr()
```

```{r}
effects |>
  _[strata == "age_cat"] |>
  _[time == 2035] |>
  ggplot() +
  aes(x = mean_mcscase45, xmin = mean_mcscase45_l, xmax = mean_mcscase45_u, y = scenario.int) +
  geom_pointrange() +
  geom_vline(xintercept = 0, linetype = "dashed") +
  facet_wrap(~age_cat) +
  theme_pubr()
```

```{r}
effects |>
  _[strata == "inc_decile"] |>
  _[time == 2035] |>
  ggplot() +
  aes(x = mean_mcscase45, xmin = mean_mcscase45_l, xmax = mean_mcscase45_u, y = scenario.int) +
  geom_pointrange() +
  geom_vline(xintercept = 0, linetype = "dashed") +
  facet_wrap(~inc_decile) +
  theme_pubr()
```
